version: '3.8'

services:
  app:
    build: .
    container_name: main
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - gradle-cache:/home/gradle/.gradle
    networks:
      - backend

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  postgres-data:
  gradle-cache:
