server:
  port: 8000

spring:
  application:
    name: deepseek_api_test

  datasource:
    url: "jdbc:postgresql://postgres:5432/${POSTGRES_DB}"
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always